// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katanomi/pkg/webhook/admission (interfaces: TriggeredByGetter)

// Package admission is a generated GoMock package.
package admission

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/katanomi/pkg/apis/meta/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockTriggeredByGetter is a mock of TriggeredByGetter interface.
type MockTriggeredByGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTriggeredByGetterMockRecorder
}

// MockTriggeredByGetterMockRecorder is the mock recorder for MockTriggeredByGetter.
type MockTriggeredByGetterMockRecorder struct {
	mock *MockTriggeredByGetter
}

// NewMockTriggeredByGetter creates a new mock instance.
func NewMockTriggeredByGetter(ctrl *gomock.Controller) *MockTriggeredByGetter {
	mock := &MockTriggeredByGetter{ctrl: ctrl}
	mock.recorder = &MockTriggeredByGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggeredByGetter) EXPECT() *MockTriggeredByGetterMockRecorder {
	return m.recorder
}

// GetTriggeredBy mocks base method.
func (m *MockTriggeredByGetter) GetTriggeredBy(arg0 runtime.Object) *v1alpha1.TriggeredBy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTriggeredBy", arg0)
	ret0, _ := ret[0].(*v1alpha1.TriggeredBy)
	return ret0
}

// GetTriggeredBy indicates an expected call of GetTriggeredBy.
func (mr *MockTriggeredByGetterMockRecorder) GetTriggeredBy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTriggeredBy", reflect.TypeOf((*MockTriggeredByGetter)(nil).GetTriggeredBy), arg0)
}
