apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8082
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9444
leaderElection:
  leaderElect: true
  resourceName: samples.pkg.katanomi.dev
