# https://docs.getwoke.tech/rules/
ignore_files:
  - .golangci.yaml

# https://docs.getwoke.tech/ignore/
rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
    alternatives:
      - allowlist
    # severity: warn # disabled to show that error is the default
