# permissions for end users to edit triggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trigger-editor-role
rules:
- apiGroups:
  - core.katanomi.dev
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.katanomi.dev
  resources:
  - triggers/status
  verbs:
  - get
