apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
    - description: >
        Cache for go modules
      name: cache
      optional: true
  tasks:
    - name: boilerplate
      params:
        - name: revision
          value: $(params.git-revision)
      taskRef:
        name: katanomi-boilerplate
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: donotsubmit
      params:
        - name: revision
          value: $(params.git-revision)
      taskRef:
        name: katanomi-donotsubmit
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: gotest
      taskRef:
        name: katanomi-gotest
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: go-style
      params:
        - name: revision
          value: $(params.git-revision)
      taskRef:
        name: katanomi-go-style
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: knative-style
      params:
        - name: ignore-filetypes
          value: '(\.png|\.drawio|\.DS_Store)$'
        - name: ignore-dirs
          value: '(^vendor/|^third_party/|^.git|kodata)'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        name: katanomi-knative-style
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: generate-version
      params:
        - name: repo-url
          value: $(params.git-url)
        - name: repo-ref
          value: $(params.git-revision)
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: katanomi-generate-version
      workspaces:
        - name: source
          workspace: source



    #################
    # code-scan
    #################
    - name: code-scan
      params:
        - name: address
          value: https://build-sonar.alauda.cn
        - name: version
          value: $(tasks.generate-version.results.semver-version)
        - name: pr-id
          value: "$(tasks.generate-version.results.pr-id)"
        - name: target
          value: "$(tasks.generate-version.results.target-branch)"
        - name: branch
          value: $(tasks.generate-version.results.branch)

      taskRef:
        kind: ClusterTask
        name: katanomi-codescan-sonarqube
      workspaces:
        - name: source
          workspace: source
      runAfter:
      - generate-version
      - gotest

    #################
    # code-scan quality gate
    #################
    - name: code-scan-quality-gate
      params:
        - name: address
          value: https://build-sonar.alauda.cn

        - name: pr-id
          value: "$(tasks.generate-version.results.pr-id)"

        - name: branch
          value: $(tasks.generate-version.results.branch)

        - name: target-branch
          value: $(tasks.generate-version.results.target-branch)

        - name: task-id
          value: $(tasks.code-scan.results.task-id)

        - name: project-key
          value: $(tasks.code-scan.results.project-key)

        - name: sonar-result-url
          value: $(tasks.code-scan.results.report-html-url)

        - name: repo-url
          value: $(params.git-url)

      taskRef:
        kind: ClusterTask
        name: katanomi-codescan-sonarqube-qualitygate
      workspaces:
        - name: source
          workspace: source
