//go:build !ignore_autogenerated

/*
Copyright 2024 The Katanomi Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/rbac/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreatedBy) DeepCopyInto(out *CreatedBy) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(v1.Subject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatedBy.
func (in *CreatedBy) DeepCopy() *CreatedBy {
	if in == nil {
		return nil
	}
	out := new(CreatedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DataMap) DeepCopyInto(out *DataMap) {
	{
		in := &in
		*out = make(DataMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMap.
func (in DataMap) DeepCopy() DataMap {
	if in == nil {
		return nil
	}
	out := new(DataMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletedBy) DeepCopyInto(out *DeletedBy) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(v1.Subject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletedBy.
func (in *DeletedBy) DeepCopy() *DeletedBy {
	if in == nil {
		return nil
	}
	out := new(DeletedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pager) DeepCopyInto(out *Pager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pager.
func (in *Pager) DeepCopy() *Pager {
	if in == nil {
		return nil
	}
	out := new(Pager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatedBy) DeepCopyInto(out *UpdatedBy) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(v1.Subject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatedBy.
func (in *UpdatedBy) DeepCopy() *UpdatedBy {
	if in == nil {
		return nil
	}
	out := new(UpdatedBy)
	in.DeepCopyInto(out)
	return out
}
