// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katanomi/pkg/plugin/types (interfaces: TestModuleLister)

// Package types is a generated GoMock package.
package types

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "github.com/katanomi/pkg/apis/meta/v1alpha1"
	zap "go.uber.org/zap"
)

// MockTestModuleLister is a mock of TestModuleLister interface.
type MockTestModuleLister struct {
	ctrl     *gomock.Controller
	recorder *MockTestModuleListerMockRecorder
}

// MockTestModuleListerMockRecorder is the mock recorder for MockTestModuleLister.
type MockTestModuleListerMockRecorder struct {
	mock *MockTestModuleLister
}

// NewMockTestModuleLister creates a new mock instance.
func NewMockTestModuleLister(ctrl *gomock.Controller) *MockTestModuleLister {
	mock := &MockTestModuleLister{ctrl: ctrl}
	mock.recorder = &MockTestModuleListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestModuleLister) EXPECT() *MockTestModuleListerMockRecorder {
	return m.recorder
}

// ListTestModules mocks base method.
func (m *MockTestModuleLister) ListTestModules(arg0 context.Context, arg1 v1alpha1.TestProjectOptions, arg2 v1alpha1.ListOptions) (*v1alpha1.TestModuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestModules", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.TestModuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestModules indicates an expected call of ListTestModules.
func (mr *MockTestModuleListerMockRecorder) ListTestModules(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestModules", reflect.TypeOf((*MockTestModuleLister)(nil).ListTestModules), arg0, arg1, arg2)
}

// Path mocks base method.
func (m *MockTestModuleLister) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockTestModuleListerMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockTestModuleLister)(nil).Path))
}

// Setup mocks base method.
func (m *MockTestModuleLister) Setup(arg0 context.Context, arg1 *zap.SugaredLogger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockTestModuleListerMockRecorder) Setup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockTestModuleLister)(nil).Setup), arg0, arg1)
}
