apiVersion: v1
data:
  loglevel.controller: info
  loglevel.controller-test: warn
  loglevel.foobar-validating: debug
  loglevel.foobar-defaulting: debug
  ## once started if a name is not present will
  ## inherit the log level with the app's name
  ## adding a new level to this configmap will only
  ## take effect when restarting the pod
  # loglevel.controller-test-bak: warn
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "console",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
kind: ConfigMap
metadata:
  namespace: pkg-system
  name: config-logging
