// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../../../testing/mock/github.com/katanomi/pkg/plugin/storage/capabilities/archive/v1alpha1/interface.go -package=v1alpha1 ArchiveCapable
//

// Package v1alpha1 is a generated GoMock package.
package v1alpha1

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/katanomi/pkg/apis/archive/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockArchiveCapable is a mock of ArchiveCapable interface.
type MockArchiveCapable struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveCapableMockRecorder
}

// MockArchiveCapableMockRecorder is the mock recorder for MockArchiveCapable.
type MockArchiveCapableMockRecorder struct {
	mock *MockArchiveCapable
}

// NewMockArchiveCapable creates a new mock instance.
func NewMockArchiveCapable(ctrl *gomock.Controller) *MockArchiveCapable {
	mock := &MockArchiveCapable{ctrl: ctrl}
	mock.recorder = &MockArchiveCapableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveCapable) EXPECT() *MockArchiveCapableMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockArchiveCapable) Aggregate(ctx context.Context, aggs v1alpha1.AggregateQuery, opts *v1alpha1.ListOptions) (*v1alpha1.AggregateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, aggs, opts)
	ret0, _ := ret[0].(*v1alpha1.AggregateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockArchiveCapableMockRecorder) Aggregate(ctx, aggs, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockArchiveCapable)(nil).Aggregate), ctx, aggs, opts)
}

// Delete mocks base method.
func (m *MockArchiveCapable) Delete(ctx context.Context, cluster, uid string, opts *v1alpha1.DeleteOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cluster, uid, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArchiveCapableMockRecorder) Delete(ctx, cluster, uid, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArchiveCapable)(nil).Delete), ctx, cluster, uid, opts)
}

// DeleteBatch mocks base method.
func (m *MockArchiveCapable) DeleteBatch(ctx context.Context, conditions []v1alpha1.Condition, opts *v1alpha1.DeleteOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, conditions, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockArchiveCapableMockRecorder) DeleteBatch(ctx, conditions, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockArchiveCapable)(nil).DeleteBatch), ctx, conditions, opts)
}

// ListRecords mocks base method.
func (m *MockArchiveCapable) ListRecords(ctx context.Context, query v1alpha1.Query, opts *v1alpha1.ListOptions) (*v1alpha1.RecordList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecords", ctx, query, opts)
	ret0, _ := ret[0].(*v1alpha1.RecordList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecords indicates an expected call of ListRecords.
func (mr *MockArchiveCapableMockRecorder) ListRecords(ctx, query, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecords", reflect.TypeOf((*MockArchiveCapable)(nil).ListRecords), ctx, query, opts)
}

// ListRelatedRecords mocks base method.
func (m *MockArchiveCapable) ListRelatedRecords(ctx context.Context, query v1alpha1.Query, opts *v1alpha1.ListOptions) (*v1alpha1.RecordList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelatedRecords", ctx, query, opts)
	ret0, _ := ret[0].(*v1alpha1.RecordList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelatedRecords indicates an expected call of ListRelatedRecords.
func (mr *MockArchiveCapableMockRecorder) ListRelatedRecords(ctx, query, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelatedRecords", reflect.TypeOf((*MockArchiveCapable)(nil).ListRelatedRecords), ctx, query, opts)
}

// Upsert mocks base method.
func (m *MockArchiveCapable) Upsert(ctx context.Context, record *v1alpha1.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockArchiveCapableMockRecorder) Upsert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockArchiveCapable)(nil).Upsert), ctx, record)
}
